services:
  # The Node.js/Express API Service
  api:
    # Instructions for building the Docker image for this service
    build:
      # The build context is the 'server' directory
      context: ./server
      # The Dockerfile to use is located in the context directory.
      dockerfile: Dockerfile
    # Maps port 5001 of the host machine to port 5001 in the container
    ports:
      - '5001:5001'
    env_file:
      - ./server/.env
    # Mounts the local './server' directory into '/app' in the container.
    # This enables live-reloading of code changes without rebuilding the image.
    volumes:
      - ./server/src:/app/src
      - ./server/package.json:/app/package.json
      - ./server/.env:/app/.env
    # Defines environment variables available to the 'api' service.
    # These are used to connect to the other services by their service names.
    environment:
      - NODE_ENV=development
      # - REDIS_URI=redis://redis:6379
      # - PORT=5001
    # # Ensures that 'mongo' and 'redis' services are started before this one.
    # depends_on:
    #   - redis
