# This is a single, unified configuration file for production on AWS.
services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
    command: node src/server.js
